export function detectLanguageFromPath(filePath: string): string {
  const extension = filePath.split('.').pop()?.toLowerCase() || '';
  
  const languageMap: Record<string, string> = {
    js: 'javascript',
    jsx: 'javascript',
    ts: 'typescript',
    tsx: 'typescript',
    py: 'python',
    rb: 'ruby',
    php: 'php',
    java: 'java',
    c: 'c',
    cpp: 'cpp',
    cc: 'cpp',
    cxx: 'cpp',
    cs: 'csharp',
    go: 'go',
    rs: 'rust',
    sh: 'bash',
    bash: 'bash',
    zsh: 'bash',
    fish: 'fish',
    ps1: 'powershell',
    html: 'html',
    htm: 'html',
    css: 'css',
    scss: 'scss',
    sass: 'sass',
    less: 'less',
    json: 'json',
    xml: 'xml',
    yaml: 'yaml',
    yml: 'yaml',
    toml: 'toml',
    ini: 'ini',
    cfg: 'ini',
    conf: 'ini',
    md: 'markdown',
    markdown: 'markdown',
    tex: 'latex',
    sql: 'sql',
    r: 'r',
    R: 'r',
    swift: 'swift',
    kt: 'kotlin',
    scala: 'scala',
    clj: 'clojure',
    cljs: 'clojure',
    hs: 'haskell',
    elm: 'elm',
    ex: 'elixir',
    exs: 'elixir',
    erl: 'erlang',
    pl: 'perl',
    pm: 'perl',
    lua: 'lua',
    vim: 'vim',
    dockerfile: 'dockerfile',
    makefile: 'makefile',
    mk: 'makefile',
  };

  return languageMap[extension] || 'text';
}

export function getLanguageDisplayName(language: string): string {
  const displayNames: Record<string, string> = {
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    python: 'Python',
    ruby: 'Ruby',
    php: 'PHP',
    java: 'Java',
    c: 'C',
    cpp: 'C++',
    csharp: 'C#',
    go: 'Go',
    rust: 'Rust',
    bash: 'Bash',
    fish: 'Fish',
    powershell: 'PowerShell',
    html: 'HTML',
    css: 'CSS',
    scss: 'SCSS',
    sass: 'Sass',
    less: 'Less',
    json: 'JSON',
    xml: 'XML',
    yaml: 'YAML',
    toml: 'TOML',
    ini: 'INI',
    markdown: 'Markdown',
    latex: 'LaTeX',
    sql: 'SQL',
    r: 'R',
    swift: 'Swift',
    kotlin: 'Kotlin',
    scala: 'Scala',
    clojure: 'Clojure',
    haskell: 'Haskell',
    elm: 'Elm',
    elixir: 'Elixir',
    erlang: 'Erlang',
    perl: 'Perl',
    lua: 'Lua',
    vim: 'Vim',
    dockerfile: 'Dockerfile',
    makefile: 'Makefile',
    text: 'Text',
  };

  return displayNames[language] || language;
}